### PR TITLE
Add input widget to enter isovalue; set initial slider position

### PR DESCRIPTION
**Pull request by pavolklacansky**
Please test on your side too.

### CODE REVIEW

**Comment by scrgiorgio** [comment]
About this line:

widgets.value->setText(cstring(widgets.slider->value()).c_str());

in the refresh, the Widget (i.e. a Viewer in an MVC pattern) should only get updates/show what's stored in the model. The model is a central repository and all connected viewers should update consequently.

Am I missing something? Why do you get the current value from another Widget/Viewer?

**Comment by pavolklacansky** [comment]
It guarantees that both apply the same range clamping of the isovalue. Potentially, the isovalue could be clamped in setIsovalue.

**Comment by scrgiorgio** [comment]
Let's say we have a server and some clients (like a workstation that is driving powerwall clients)

The clients receive the modification from the network. Instead of refreshing their view "following" the model they singularly do:

widgets.value->setText(cstring(widgets.slider->value()).c_str());

so each one will have a different/not-in-sync/wrong value. 
Could it happen?

**Comment by pavolklacansky** [comment]
I do not think so, because the above line would update the value in the slider widget. I am okay if you want to clamp the value before passing it to the slider widget and use the same value into the input widget.

**Comment by scrgiorgio** [comment]
kk

**Pull request merged**
