### PR TITLE
Add initial stable API with tests

### PR DESCRIPTION
**Pull request by klacansky**

### CODE REVIEW

**Comment by klacansky** [comment]
Any progress on merging it? Thanks!

**Comment by scrgiorgio** [comment]
Sorry if I am late on this. My suggestions:

- please `git pull` / `git rebase` since there were bugs with ARCO vs IDX caching (and cache_dir too) that have been fixed in recent commits. All changes should not conflict with your modifications.

- do not rename `create_idx` to `create_dataset` but create an "alias". There is code around (external to this repo, in particular in Jupyter Notebooks) that uses create_idx. In general, always prefer non-breaking API changes.

- do not add the `Dataset` python class to `dataset.py`. There is already a Dataset class in C++ and having the same name in Python can be confusing (or difficult to handle with SWIG-generated code), in particular in the case of "from OpenVisus import *".

**Comment by klacansky** [comment]
I renamed the function and dataset, and also updated the test.

https://github.com/klacansky/OpenVisus/actions/runs/4370728503

**Comment by scrgiorgio** [comment]
All ok. 
Don't get the name "Dataset1" (usually I prefer self-describing names, what does "1" stands for?)

**Comment by klacansky** [comment]
Direct3D uses that for versioning, so when there are changes, you return Dataset2, Dataset3, ...

What name would you prefer?

**Comment by klacansky** [comment]
Can you push a new tag please? Thanks!

**Comment by scrgiorgio** [comment]
Just pushed.

I was thinking about adding a file "Libs/swig/stable_api" so people can do:

```
from OpenVisus.stable_api import Dataset,LoadDataset # etc...
```

this way we can have name overlapping.
(could be `stable_api_v<n>` as well)

**Comment by klacansky** [comment]
Interesting. I would then maybe make the experimental API like (so that most users have the simple `import OpenVisus as ov`)
```
from OpenVisus.experimental_api import Dataset,LoadDataset # etc...
```

**Pull request merged**
