### PR TITLE
Disable C++ logging in Python package

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by klacansky** [comment]
I added support for seeing the logs in Python. I am not sure if the GIL slows things down much. Can you carefully review the code please?

You can still get logging by doing this before importing OpenVisus.

```
import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
import OpenVisus as ov
```

**Comment by scrgiorgio** [comment]
There is only one "issue": the standard distribution (PyPI,conda) relies on python (i.e., they import OpenVisus using the OpenVisus python package), so by default this way, we will not get any log messages (unless the Python logger is properly configured). 

If so, in case of user problems, we will not have any logs/clues what is wrong and it will be more difficult to fix stuff.

Apart from that, all seems fine (NOTE: I am not an expert on Python API; I usually let swig generate the wrapping code).

**Comment by klacansky** [comment]
I added an example how to enable logging. I think if somebody reports a bug, they could enable logging and share the output.

**Comment by scrgiorgio** [comment]
it will be difficult to ask final users to modify any code.

**Comment by klacansky** [comment]
What do you think we should do? I was thinking to log into a file, and that does not seem right either. For example, some other library may use OpenVisus internally and creating log files automatically may not be desired.

**Pull request merged**
